-- 🎥 Requêtes Snowflake pour la Démonstration Vidéo
-- Pipeline Sneakers Kafka → Snowflake

-- ===== SETUP =====
USE WAREHOUSE TEACH_WH;
USE DATABASE RETAIL_LAB;
USE SCHEMA STG;

-- ===== 1. VOIR LES DERNIÈRES COMMANDES =====
SELECT 
    ORDER_ID,
    BRAND,
    MODEL,
    COLOR,
    SIZE,
    TOTAL_AMOUNT,
    CUSTOMER_NAME,
    PROCESSED_AT
FROM STREAMING_ORDERS 
ORDER BY PROCESSED_AT DESC 
LIMIT 10;

-- ===== 2. STATISTIQUES PAR MARQUE =====
SELECT 
    BRAND,
    COUNT(*) as NB_COMMANDES,
    ROUND(AVG(TOTAL_AMOUNT), 2) as PRIX_MOYEN,
    ROUND(SUM(TOTAL_AMOUNT), 2) as CHIFFRE_AFFAIRES
FROM STREAMING_ORDERS 
GROUP BY BRAND 
ORDER BY CHIFFRE_AFFAIRES DESC;

-- ===== 3. TOP TAILLES VENDUES =====
SELECT 
    SIZE,
    COUNT(*) as NB_VENTES,
    ROUND(AVG(TOTAL_AMOUNT), 2) as PRIX_MOYEN
FROM STREAMING_ORDERS 
GROUP BY SIZE 
ORDER BY NB_VENTES DESC;

-- ===== 4. COMMANDES EN TEMPS RÉEL (dernières 5 minutes) =====
SELECT 
    BRAND || ' ' || MODEL || ' Size ' || SIZE as PRODUIT,
    TOTAL_AMOUNT,
    CUSTOMER_NAME,
    PROCESSED_AT
FROM STREAMING_ORDERS 
WHERE PROCESSED_AT >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP())
ORDER BY PROCESSED_AT DESC;

-- ===== 5. ANALYSE PAR CANAL DE VENTE =====
SELECT 
    CHANNEL,
    COUNT(*) as NB_COMMANDES,
    ROUND(SUM(TOTAL_AMOUNT), 2) as CA_TOTAL
FROM STREAMING_ORDERS 
GROUP BY CHANNEL;

-- ===== 6. ÉVOLUTION TEMPS RÉEL (refresh cette requête) =====
SELECT 
    DATE_TRUNC('MINUTE', PROCESSED_AT) as MINUTE,
    COUNT(*) as COMMANDES_PAR_MINUTE,
    ROUND(SUM(TOTAL_AMOUNT), 2) as CA_PAR_MINUTE
FROM STREAMING_ORDERS 
WHERE PROCESSED_AT >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('MINUTE', PROCESSED_AT)
ORDER BY MINUTE DESC;

-- ===== 7. COMPARAISON DONNÉES BATCH vs STREAMING =====
-- Données batch (table ORDERS)
SELECT 'BATCH' as SOURCE, COUNT(*) as NB_RECORDS FROM ORDERS
UNION ALL
-- Données streaming (table STREAMING_ORDERS)  
SELECT 'STREAMING' as SOURCE, COUNT(*) as NB_RECORDS FROM STREAMING_ORDERS;

-- ===== 8. DÉTAIL D'UNE COMMANDE =====
SELECT *
FROM STREAMING_ORDERS 
ORDER BY PROCESSED_AT DESC 
LIMIT 1;



